// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmxkfxtfxevpkgvusfze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRteGtmeHRmeGV2cGtndnVzZnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTk0MjQsImV4cCI6MjA2NDU5NTQyNH0.fMQQ_D4keJi0aLwR8tBej_kg2fkeaAXq9XsJguhmkr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);